name: QuickBuild

on:
  schedule:
    - cron: '00 00 * * *'
  push:
    branches:
      - '*'
    tags: '*'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Build-Linux
        run: julia --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ADCME"); using ADCME; install_adept(); ADCME.precompile()'
  MacOSX:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          sudo: false
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Build-MacOSX
        run: julia --color=yes -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate(); Pkg.build("ADCME"); using ADCME; install_adept(); ADCME.precompile()'
  Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
      - name: Chocolatey Action
        uses: crazy-max/ghaction-chocolatey@v1.2.2     
        with:
          args: install visualstudio2017community
      - name: Chocolatey Action
        uses: crazy-max/ghaction-chocolatey@v1.2.2     
        with:
          args: install visualstudio2017-workload-nativedesktop
      - uses: julia-actions/julia-buildpkg@latest


